### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by shruthi-22** [surya-veer/movement-tracking#7]
can you say what does detectmultiscale return ?

How is nose detected ?

**Comment by surya-veer** [comment]
Hi @shruthi-22, detectmultiscale returns the list of the detected object as a rectangle. [read this for more](https://docs.opencv.org/3.1.0/d7/d8b/tutorial_py_face_detection.html#gsc.tab=0)

So I am doing as an estimation to detect nose, since the face is symmetric and the nose lies on the centre of eyebrow line and chin.<be>
Now assume 
face boundary = (x1,y1) and (x2, y2)
nose coordinates will ((x1+x2)/2, (y1+y2)/2)
